### 모델 테스트

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
from tensorflow.keras.models import load_model  # model 사용

In [2]:
model = load_model('./Pinterest.h5')

In [3]:
X = np.array([[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0]])
Y = [0]

print(X)

[[1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0]]


In [4]:
p=model.predict(X)
print(p)

[[0.6499224  0.00782875 0.01280042 0.12066945 0.20877898]]


In [5]:
print(p*100)
print(np.max(p*100))
print(np.argmax(p*100))

[[64.99223    0.7828749  1.2800415 12.066945  20.877897 ]]
64.99223
0


In [6]:
# 0: 강아지, 1: 카페, 2: 가을, 3: 한우, 4: 꽃  
index = np.argmax(p) 
print('-> index: ', index) # 0 ~ 4
per = round(np.max(p) * 100, 3)
print('-> per: ', per) 

if index == 0:
    label = '강아지'
elif index == 1:
    label = '카페'
elif index == 2:
    label = '가을'
elif index == 3:
    label = '한우'
elif index == 4:
    label = '꽃'

result = {}
# 종류가 5개임으로 균등한 분할은 20%임으로 20% 초과시 추천
if per >= 20:
    result = {"label": label, "per": per}
else:
    result = {"label": f'가장 인접한 추천: {label}', "per": per}

print(result)

# [[0.35821876 0.28507757 0.35670367]]: 1번만 전부 선택 했는데 확률이 너무 작은 값임.

-> index:  0
-> per:  64.992
{'label': '강아지', 'per': 64.992}


In [7]:
# 함수 기반의 처리
def recommend(X, Y):
    data = np.array([np.array(X)]) # ndarray 타입의 2차원이어야함
    p = model.predict(data)  # 모델 사용, 2차원 데이터 전달
    
    index = np.argmax(p) 
    per = round(np.max(p) * 100, 1)
    print(f'-> index: {index}  per: {per} %', end=' ')

    if index == 0:
        label = '강아지'
    elif index == 1:
        label = '카페'
    elif index == 2:
        label = '가을'
    elif index == 3:
        label = '한우'
    elif index == 4:
        label = '꽃'
    
    if np.max(p*100) > 20:
        print(label + ' 추천 필요') 
    else:
        print('구별이 확실하지 않아 추천이 어렵습니다.')
        print(f'가장 인접한 추천: {label}')

In [8]:
# 0: 강아지, 1: 카페, 2: 가을, 3: 한우 0,0,0,1,0, 4: 꽃  
recommend([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0], 0)
recommend([0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0], 1)
recommend([0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0], 2)
# 강아지 4번 카페 1번
recommend([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0], 0)
# 강아지 3번 카페 2번
recommend([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0], 0)
# 강아지 2번 카페 3번
recommend([1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0], 0)
# 강아지 1번 카페 4번
recommend([1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0], 0)
# 한우 3번, 꽃 2번
recommend([0,0,0,1,0,
           0,0,0,0,1,
           0,0,0,1,0,
           0,0,0,0,1,
           0,0,0,1,0], 0)
# 한우 3번, 강아지1번, 꽃 2번
recommend([0,0,0,1,0,
           0,0,0,0,1,
           0,0,0,1,0,
           1,0,0,0,0,
           0,0,0,1,0], 0)

-> index: 0  per: 65.0 % 강아지 추천 필요
-> index: 1  per: 64.6 % 카페 추천 필요
-> index: 2  per: 71.0 % 가을 추천 필요
-> index: 0  per: 46.7 % 강아지 추천 필요
-> index: 0  per: 28.7 % 강아지 추천 필요
-> index: 1  per: 41.8 % 카페 추천 필요
-> index: 1  per: 58.7 % 카페 추천 필요
-> index: 3  per: 49.6 % 한우 추천 필요
-> index: 3  per: 68.8 % 한우 추천 필요
