In [1]:
%autosave 0
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
import pandas as pd

from tensorflow.keras.utils import to_categorical  # one-hot 엔코딩
from sklearn.preprocessing import LabelEncoder     # 명목형 척도 정수화 
from tensorflow.keras.models import load_model     # model 사용

Autosave disabled


In [2]:
model = load_model('./Iris.h5')

OSError: No file or directory found at ./Iris.h5

In [ ]:
df = pd.read_csv('./iris_use.csv', names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.0          3.5           1.3          0.3  Iris-setosa
1           4.5          2.3           1.3          0.3  Iris-setosa
2           4.4          3.2           1.3          0.2  Iris-setosa
3           5.0          3.5           1.6          0.6  Iris-setosa
4           5.1          3.8           1.9          0.4  Iris-setosa


In [ ]:
data = df.values
print(type(data))
print(len(data))
X = data[:, 0:4].astype(float)  # 독립 변수, 정의역
Y_str = data[:, 4]              # 종속 변수, 치역 
print(Y_str)

<class 'numpy.ndarray'>
30
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']


In [ ]:
# 문자 레이블을 숫자화, 문자열을 알파벳순으로 그룹화한후 0부터 숫자로 변환
encoder = LabelEncoder()
encoder.fit(Y_str)
Y = encoder.transform(Y_str)
print(Y)

Y_encoded = to_categorical(Y) # one-hot-encoding, 해당 index만 1로 변경
print(Y_encoded[0])
print(Y_encoded[10])
print(Y_encoded[20])

# LabelEncoder() 엔코더 사용시 모든 그룹의 데이터를 통합하여 진행 권장
# CSV 훈련: A, B, C  CSV 테스트: A, B, D
#           0  1  2              0  1  ?  
# CSV A, B, C, D 모두 통합후 -> 엔코더 적용 -> 데이터 훈련, 테스트로 분할
#     1  2  3  4

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


In [ ]:
print(encoder.inverse_transform([0, 1, 2])) # Label 확인

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [ ]:
# Iris-setosa: 0, Iris-versicolor: 1, Iris-virginica: 2
p = model.predict(X)  # 테스트 데이터 30건
print('p.shape:', p.shape)
print('데이터:', X[0]) # 첫번째 데이터행

p.shape: (30, 3)
데이터: [5.  3.5 1.3 0.3]


In [ ]:
# 확률 0 ~ 1사이의 실수값
print('예측값:', p[0]) 
print('예측값: {0:.2f}% {1:.2f}% {2:.2f}%'.format((p[0][0]*100), (p[0][1]*100), (p[0][2]*100))) 
print('LabelEncoder: ', Y[0])
print('One-hot-encoding: ', Y_encoded[0])
print(np.argmax(p[0]))  # 가장 큰값의 index
print(Y_str[0])         # 첫번째 품종

예측값: [0.6113242  0.24229555 0.14638034]
예측값: 61.13% 24.23% 14.64%
LabelEncoder:  0
One-hot-encoding:  [1. 0. 0.]
0
Iris-setosa


In [ ]:
for item in p: # 2차원 배열에서 1행씩 산출
    print(item)
    print('최대값:', np.max(item), '-> index:', np.argmax(item))
    # 최대값 -> 최대값이 있는 index

[0.6113242  0.24229555 0.14638034]
최대값: 0.6113242 -> index: 0
[0.5305855  0.29289058 0.17652388]
최대값: 0.5305855 -> index: 0
[0.5908211  0.25454333 0.1546356 ]
최대값: 0.5908211 -> index: 0
[0.5607307  0.2717654  0.16750388]
최대값: 0.5607307 -> index: 0
[0.58674216 0.26676098 0.14649686]
최대값: 0.58674216 -> index: 0
[0.5772849  0.26355332 0.1591618 ]
최대값: 0.5772849 -> index: 0
[0.6297056  0.23761977 0.13267463]
최대값: 0.6297056 -> index: 0
[0.5948655  0.25369203 0.15144245]
최대값: 0.5948655 -> index: 0
[0.63484526 0.23341715 0.13173757]
최대값: 0.63484526 -> index: 0
[0.61214846 0.24476643 0.14308506]
최대값: 0.61214846 -> index: 0
[0.22142005 0.4649825  0.31359738]
최대값: 0.4649825 -> index: 1
[0.21214859 0.4512949  0.33655655]
최대값: 0.4512949 -> index: 1
[0.18839592 0.46158183 0.35002223]
최대값: 0.46158183 -> index: 1
[0.19086203 0.42990804 0.3792299 ]
최대값: 0.42990804 -> index: 1
[0.18264084 0.44901818 0.36834097]
최대값: 0.44901818 -> index: 1
[0.19346781 0.43273553 0.3737966 ]
최대값: 0.43273553 -> index: 1
[

In [ ]:
# softmax 함수의 값이 1이되는지 확인
# 컴퓨터는 내부적으로 정수 연산이라 미세한 오차 발생
for item in p:
    print(item, ' 합계: {0:0.0f}'.format(np.sum(item)))

[0.6113242  0.24229555 0.14638034]  합계: 1
[0.5305855  0.29289058 0.17652388]  합계: 1
[0.5908211  0.25454333 0.1546356 ]  합계: 1
[0.5607307  0.2717654  0.16750388]  합계: 1
[0.58674216 0.26676098 0.14649686]  합계: 1
[0.5772849  0.26355332 0.1591618 ]  합계: 1
[0.6297056  0.23761977 0.13267463]  합계: 1
[0.5948655  0.25369203 0.15144245]  합계: 1
[0.63484526 0.23341715 0.13173757]  합계: 1
[0.61214846 0.24476643 0.14308506]  합계: 1
[0.22142005 0.4649825  0.31359738]  합계: 1
[0.21214859 0.4512949  0.33655655]  합계: 1
[0.18839592 0.46158183 0.35002223]  합계: 1
[0.19086203 0.42990804 0.3792299 ]  합계: 1
[0.18264084 0.44901818 0.36834097]  합계: 1
[0.19346781 0.43273553 0.3737966 ]  합계: 1
[0.19446208 0.4389139  0.366624  ]  합계: 1
[0.26893497 0.42812946 0.30293557]  합계: 1
[0.21007757 0.46154273 0.32837978]  합계: 1
[0.20772669 0.41872448 0.37354884]  합계: 1
[0.07539626 0.29575977 0.62884396]  합계: 1
[0.11242716 0.35726422 0.5303086 ]  합계: 1
[0.0940121  0.37457755 0.53141034]  합계: 1
[0.11294315 0.37683332 0.5102235 ]

In [ ]:
# Iris-setosa: 0, Iris-versicolor: 1, Iris-virginica: 2
def decode(data):  # data: 1차원 배열, predict는 2차원 배열을 리턴함
    index = np.argmax(data) # 최대값의 index를 찾아줌
    if index == 0:
        label = 'Iris-setosa'
    elif index == 1:
        label = 'Iris-versicolor'
    elif index == 2:
        label = 'Iris-virginica'
        
    return label

In [ ]:
print(len(p))
for i in range(len(p)):
    print('Target(실제값):', Y_str[i], ' Y hat(예측값):', decode(p[i]))

30
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y h

In [ ]:
# input 함수의 사용
# 5.1,3.5,1.4,0.2
src = input('꽃받침 길이, 꽃받침 넓이, 꽃잎 길이, 꽃잎 넓이를 입력하세요.')
print(type(src))
print(src)

꽃받침 길이, 꽃받침 넓이, 꽃잎 길이, 꽃잎 넓이를 입력하세요.5.1,3.5,1.4,0.2
<class 'str'>
5.1,3.5,1.4,0.2


In [ ]:
data = np.array(src.split(','), dtype=float) # 1차원 텐서
print(data.shape)
print(data)

(4,)
[5.1 3.5 1.4 0.2]


In [ ]:
X = np.array([data])  # 2차원 텐서(배열)로 변환
print(X.shape)
print(X)
p = model.predict(X)  # 2차원 배열 대입
print('p:', p)

for i in range(len(p)):
    print('예측값:', decode(p[i])) # [[0.6227252  0.23900516 0.13826966]]

(1, 4)
[[5.1 3.5 1.4 0.2]]
p: [[0.6227252  0.23900516 0.13826966]]
예측값: Iris-setosa
