In [5]:
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
from tensorflow.keras.models import load_model  # model 사용


In [6]:
model = load_model('./Pinterest.h5')

OSError: No file or directory found at ./Pinterest.h5

In [ ]:
X = np.array([[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0]])
Y = [0]

print(X)

NameError: name 'np' is not defined

In [ ]:
p = model.predict(X)
print(p)

In [ ]:
print(p*100)
print(np.max(p*100))
print(np.argmax(p*100))

In [ ]:
# 0: 강아지, 1: 카페, 2: 가을, 3: 한우, 4: 꽃  
index = np.argmax(p) 
print('-> index: ', index) # 0 ~ 4
per = round(np.max(p) * 100, 3)
print('-> per: ', per) 

if index == 0:
    label = '강아지'
elif index == 1:
    label = '카페'
elif index == 2:
    label = '가을'
elif index == 3:
    label = '한우'
elif index == 4:
    label = '꽃'

result = {}
# 종류가 5개임으로 균등한 분할은 20%임으로 20% 초과시 추천
if per >= 20:
    result = {"label": label, "per": per}
else:
    result = {"label": f'가장 인접한 추천: {label}', "per": per}

print(result)

# [[0.35821876 0.28507757 0.35670367]]: 1번만 전부 선택 했는데 확률이 너무 작은 값임.

In [4]:
# 함수 기반의 처리
def recommend(X, Y):
    data = np.array([np.array(X)]) # ndarray 타입의 2차원이어야함
    p = model.predict(data)  # 모델 사용, 2차원 데이터 전달
    
    index = np.argmax(p) 
    per = round(np.max(p) * 100, 3)
    print('-> index: ', index, 'per: ', per) # 0 ~ 4

    if index == 0:
        label = '강아지'
    elif index == 1:
        label = '카페'
    elif index == 2:
        label = '가을'
    elif index == 3:
        label = '한우'
    elif index == 4:
        label = '꽃'
    
    if np.max(p*100) > 20:
        print(label + ' 추천 필요') 
    else:
        print('구별이 확실하지 않아 추천이 어렵습니다.')
        print(f'가장 인접한 추천: {label}')

In [30]:
data = np.loadtxt('./train.csv', delimiter=',', skiprows=1, dtype=np.float64)
print(data.shape)
print(type(data))
print(data[:5])
Y = Y.astype(np.int32)
print(Y[:15])

(100, 26)
<class 'numpy.ndarray'>
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
  0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.
  0. 2.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.
  0. 3.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  1. 4.]]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [31]:
X = data[:,0:25] # Pandas -> Numpy array
Y = data[:,25] # Pandas -> Numpy array
print(X.shape)
print(Y.shape)

(100, 25)
(100,)


In [32]:
Y_encoded = to_categorical(Y)
print(X[0])
print(Y[0])
print(Y_encoded[0:5])

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 0.]
0.0
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
# train_test_split 분할을 통한 훈련, 검증, 테스트 데이터의 분리
seed = 0
# 90%: 분할대기, 10%: 테스트
x_train_all, x_test, y_train_all, y_test = train_test_split(X, Y_encoded,
                                                        stratify=Y_encoded,
                                                        test_size=0.1,
                                                        random_state=seed)
# 나머지 데이터 90%를 분할, 80%: 훈련, 20%: 검증
x_train, x_val, y_train, y_val = train_test_split(x_train_all, y_train_all,
                                                  stratify=y_train_all,
                                                  test_size=0.2,
                                                  random_state=seed)

print(y_val)
print(y_val.shape)
# Iris-setosa: 0, Iris-versicolor: 1, Iris-virginica: 2

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
(18, 5)


In [39]:
SEED = 0
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_DETERMINISTIC_OPS'] = '1'

tf.random.set_seed(SEED) # Global seed, 가중치, 편향이 일정하게 변경됨
np.random.seed(SEED)
random.seed(SEED)

model = Sequential()
model.add(Dense(20, input_dim=4, activation='relu')) # 기울기 소실 방지
model.add(Dense(10, activation='relu')) # 기울기 소실 방지
model.add(Dense(5, activation='softmax')) # 0 ~ 1사이의 확률, 합 1
model.compile(optimizer='adam', loss='categorical_crossentropy', 
              metrics=['accuracy'])
model.summary()

es= EarlyStopping(monitor='loss', patience=1, restore_best_weights=True)

mcp= ModelCheckpoint(filepath='./Pinterest.h5', monitor='val_accuracy',
                    verbose=1, save_best_only=True)

start = time.time()
hist = model.fit(x_train, y_train, validation_data=(x_val, y_val), shuffle=True,
                epochs=100, batch_size=1, callbacks=[es, mcp])
end=time.time()
print('Runtime: {0:.0f} 초'.format(end-start))

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 20)                100       


                                                                 
 dense_19 (Dense)            (None, 10)                210       
                                                                 
 dense_20 (Dense)            (None, 5)                 55        
                                                                 
Total params: 365
Trainable params: 365
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100


ValueError: in user code:

    File "c:\Users\psy02\anaconda3\envs\ai\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\psy02\anaconda3\envs\ai\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\psy02\anaconda3\envs\ai\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\psy02\anaconda3\envs\ai\lib\site-packages\keras\engine\training.py", line 859, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\psy02\anaconda3\envs\ai\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\psy02\anaconda3\envs\ai\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_6" is incompatible with the layer: expected shape=(None, 4), found shape=(1, 25)
